export default [
  "Tom made a list of things he wanted to do before he died.",
  "A big bomb fell, and a great many people lost their lives.",
  "Why are you making such a big deal about it?",
  "I always list what I need before I go shopping.",
  "How big of an idiot are you?",
  "While the man was hunting the deer ran through the forest.",
  "Carl won the spelling bee and got a trophy!",
  "What do you see?",
  "Do you have any big plans for the weekend?",
  "Al went to the animal shelter and got four cats!",
  "Are trees green or blue?",
  "Shape up, or ship out!",
  "Moving to the next step is daunting.",
  "I like asparagus and brussel sprouts.",
  "You can see the blood vessel on her eyelid.",
  "What day is today?",
  "Hold on I need at least a few minutes!",
  "Don't worry about it!",
  "That man is holding a gun!",
];
